#para utilização do cors globalmente#
cors:
  originPatterns: http://localhost:3000,http://localhost:8080
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 1000 * 60 * 60
spring:
  datasource:
    #infos para conexão ao database#
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_spring_boot_estudos?useTimezone=true&serverTimezone=UTC
    username: root
    password: "####"
  jpa:
    hibernate:
      #config para geração do ddl a partir do hibernate#
      ddl-auto: none
    properties:
      hibernate:
        #config do dicionario a ser usado neste caso o mysql#
        dialect: org.hibernate.dialect.MySQLDialect
      #config para exibição do sql criado a partir do hibernate#
      show-sql: false
#config para documentação#
springdoc:
  #definindo padrão de path a ser documentados pelo swagger#
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true